import { Alert } from '../types';

export const mockAlerts: Alert[] = [
  {
    id: 'ALT-001',
    type: 'weather',
    severity: 'high',
    title: 'Severe Storm in Indian Ocean',
    description: 'Category 4 cyclone approaching shipping lanes between Singapore and Dubai',
    affectedShipments: 3,
    source: 'NOAA Weather Service',
    timestamp: '2024-04-08 14:32',
    action: 'Recommend rerouting via alternative routes',
  },
  {
    id: 'ALT-002',
    type: 'port',
    severity: 'high',
    title: 'Port Strike at Rotterdam',
    description: 'Labor dispute has suspended cargo operations at Rotterdam Port',
    affectedShipments: 5,
    source: 'Port Authority',
    timestamp: '2024-04-08 12:15',
    action: 'Divert shipments to Hamburg or Antwerp',
  },
  {
    id: 'ALT-003',
    type: 'carrier',
    severity: 'medium',
    title: 'Vessel Delay - MSC Gülsün',
    description: 'Engine trouble reported, estimated delay of 24-48 hours',
    affectedShipments: 2,
    source: 'MSC Fleet Management',
    timestamp: '2024-04-08 10:47',
    action: 'Update ETAs and notify consignees',
  },
  {
    id: 'ALT-004',
    type: 'demand',
    severity: 'low',
    title: 'Unexpected Demand Spike',
    description: 'Electronics sector showing 15% increased orders in North America',
    affectedShipments: 12,
    source: 'Market Intelligence',
    timestamp: '2024-04-08 09:22',
    action: 'Consider expedited shipping routes',
  },
  {
    id: 'ALT-005',
    type: 'carrier',
    severity: 'medium',
    title: 'Fuel Surcharge Announced',
    description: 'All major carriers implementing 3.2% fuel surcharge effective immediately',
    affectedShipments: 23,
    source: 'Shipping Industry News',
    timestamp: '2024-04-08 08:30',
  },
];
