import { Shipment } from '../types';

export const mockShipments: Shipment[] = [
  {
    id: 'SHP-001',
    origin: 'Shanghai Port',
    destination: 'Los Angeles Port',
    status: 'on-time',
    riskScore: 12,
    eta: '2024-04-15 14:30',
    carrier: 'Maersk Line',
    progress: 65,
  },
  {
    id: 'SHP-002',
    origin: 'Rotterdam Port',
    destination: 'New York Port',
    status: 'at-risk',
    riskScore: 68,
    eta: '2024-04-12 08:00',
    carrier: 'CMA CGM',
    progress: 45,
  },
  {
    id: 'SHP-003',
    origin: 'Singapore Port',
    destination: 'Dubai Port',
    status: 'delayed',
    riskScore: 85,
    eta: '2024-04-18 22:15',
    carrier: 'MSC',
    progress: 38,
  },
  {
    id: 'SHP-004',
    origin: 'Hamburg Port',
    destination: 'Singapore Port',
    status: 'on-time',
    riskScore: 18,
    eta: '2024-04-20 10:45',
    carrier: 'Hapag-Lloyd',
    progress: 52,
  },
  {
    id: 'SHP-005',
    origin: 'Hong Kong Port',
    destination: 'Rotterdam Port',
    status: 'delivered',
    riskScore: 0,
    eta: '2024-04-08 16:20',
    carrier: 'ONE',
    progress: 100,
  },
  {
    id: 'SHP-006',
    origin: 'Port Said',
    destination: 'Los Angeles Port',
    status: 'at-risk',
    riskScore: 72,
    eta: '2024-04-14 09:00',
    carrier: 'Evergreen',
    progress: 55,
  },
];
